AudereNow/audere

- FluStudy_au/src/native/rdtReader.tsx
This property is called `testStripDetected` in native code, not `testStripFound`:
https://github.com/AudereNow/audere/blob/0fe31f018f4071f8f30e6502379b74e4d8c72120/FluStudy_au/ios/fluathome/RDTView.mm#L65
https://github.com/AudereNow/audere/blob/0fe31f018f4071f8f30e6502379b74e4d8c72120/FluStudy_au/android/app/src/main/java/host/exp/exponent/RDTReader.java#L111
I was trying to use this property to automatically turn off the flash when the test strip is detected yet the picture is overexposed, but @smeds1 found that it wasn't working.
> FEV-1049 Fix native callback property name

- FluStudy_au/ios/fluathome/RDTReader/ImageProcessor.h
- FluStudy_au/ios/fluathome/RDTReader/ImageProcessor.mm
- FluStudy_au/ios/fluathome/RDTView.mm
- FluStudy_au/ios/fluathome/RDTViewManager.mm
- FluStudy_au/src/native/rdtReader.tsx
- FluStudy_au/src/ui/components/flu/RDTReader.tsx
- FluStudy_au/src/util/tracker.ts
The first time we get a memory warning on iOS, set the `frameImageScale` to 0.5. If we get another warning, go back to the old behavior (i.e. either ignore it or skip to manual capture, depending on the remote config).
This only affects iOS, since we don't get memory warnings on Android, and Android runs at the lower resolution by default anyway.
I verified that iOS capture still seems to work at the lower resolution, though perhaps a bit slower. I wasn't able to trigger the memory warning to test that, but I did check that changing the scale in the middle of a capture session still allowed for successful captures, and reduced memory usage by ~25MB.
> FEV-1176 Reduce RDT processing resolution on memory warning

- FluApi/db/migrations/nonpii/20190829183322-add-cough-expert-read.js
- FluApi/src/endpoints/webPortal/auth.ts
- FluApi/src/endpoints/webPortal/endpoint.ts
- FluApi/src/endpoints/webPortal/rdtPhotos.ts
- FluApi/src/endpoints/webPortal/templates/rdtPhotos.html
- FluApi/src/models/db/cough.ts
- FluApi/src/services/dataPipelineService.ts
Show a form alongside cough photos for Sam (or whoever else has permission) to enter their interpretation of a test strip. This data will be used by us and/or Ubicomp to assess the accuracy of automatic interpretation.
> Add form for setting "expert read" data on cough photos

- EbPhotoSite/src/PatientDetailPage.tsx
This got lost during a merge conflict or something, adding it back.
> Add PhotoPane back to patient details page

- .circleci/config.yml
Four Sniffles build attempts in a row failed because the `expo build:ios` step would get stuck during publish and then timeout after 10 minutes. (https://circleci.com/gh/AudereNow/audere/621 as well as builds 617, 618, 619)
Previously when `expo publish` hung during the publish, we added the `--max-workers 2` switch which fixed that. See FEV-598 or https://github.com/AudereNow/learn/pull/1132 
The problem is that `expo build:ios` doesn't recognize the `--max-workers` switch. 
Fixed this by breaking up `expo build:ios` (which does publish then build binary) into `expo publish --max-workers 2` and then `expo build:ios --no-publish`.
> FEV-608 Fix sniffles build hanging at expo build:ios

- FluApi/db/migrations/nonpii/20190905193624-add-contains-pii.js
- FluApi/src/endpoints/webPortal/rdtPhotos.ts
- FluApi/src/endpoints/webPortal/templates/barcodes.html
- FluApi/src/endpoints/webPortal/templates/rdtPhotos.html
- FluApi/src/models/db/cough.ts
Adds the following a question on the cough photo page, and a table to store the results.  Might be unnecessary, but you can answer one question without answering the other, and that was slightly simpler with a separate table:
Since it can take some time to manually edit PII out of photos, this allows us to quickly review photos for PII, and only share photos that are known to be clean. Later when photos containing PII get replaced, those surveys can be shared with external partners as well.
This PR also adds columns to the list page showing whether the photo was automatically or manually captured, the expert read result, and whether there's PII. It also forbids access to surveys that contain PII, or have not yet been reviewed for PII, for users who just have the basic `coughPhotosAccess` …
> FEV-1130 Add PII question to cough photos expert read form

- FluApi/src/endpoints/coughGiftcardApi.ts
Addressing @rightparen's comment in https://github.com/AudereNow/audere/pull/204#discussion_r327376278
> Filter out empty barcode prefixes

- FluStudy_au/package.json
- FluStudy_au/src/transport/index.ts
Also, respect the `REACT_NATIVE_USE_LOCAL_SERVER` flag even if dev mode is turned off.
> Do not run automation builds in dev mode

- .circleci/config.yml
Using the CircleCI Xcode 11.1.0 image to build Chills, to fix the 
```
/Users/distiller/repo/FluStudy_us/ios/Pods/ExpoKit/ios/Exponent/Kernel/Views/EXAppViewController.m:398:10: property 'overrideUserInterfaceStyle' not found on object of type 'EXAppViewController *'; did you mean 'preferredUserInterfaceStyle'?
self.overrideUserInterfaceStyle = [self _userInterfaceStyleForString:userInterfaceStyle];
^
```
build error in https://circleci.com/gh/AudereNow/audere/1044
> FEV-1219 Update CircleCI to use XCode 11

- FluApi/src/app.ts
I believe that the chills api is breaking cough giftcards, because we only initialize firebase once:
https://github.com/AudereNow/audere/blob/e7776a8b8da6c78d261f44d1a10d0821df93e5fd/FluApi/src/external/firebase.ts#L176-L189 If chills happens to initialize first, all the queries that are meant for cough hit chills instead. The cough giftcards api checks that the user's doc id exists in firebase before issuing a giftcard, but it won't find the doc ids if it's looking in the chills app.
This PR just disables the chills endpoints because we're not using them yet.
See https://github.com/AudereNow/audere/pull/352 for a real fix
> Disable chills api endpoints to fix cough

- FluApi/src/endpoints/webPortal/templates/chillsRdtPhotos.html
The chills versions of these endpoints were already set up, just need to update the template to use them: https://github.com/AudereNow/audere/blob/61c4c9a2331190e3d93d1c3c77c818ef9710c70f/FluApi/src/endpoints/webPortal/endpoint.ts#L235-L248
> Use chills urls for form actions

- FluApi/src/endpoints/webPortal/coughRdtPhotos.ts
- FluApi/src/endpoints/webPortal/templates/barcodes.html
This PR adds another column on this cough photos list page showing the PII review notes:
> Show PII review notes on cough photos list page

- FluStudy_us/android/app/src/main/java/host/exp/exponent/CameraController.java
Possible that an in-progress capture request is triggered after the cameraClose() call. We should catch those cases and not perform them.
> Guard against incoming camera requests after camera is closed

- FluStudy_us/src/ui/components/Questions.tsx
The previous checkin for FEV-1520 caused two regressions:
1) A required question with SurveyQuestionType.Text wasn't considered valid
2) Showing the zip code field for the first time could crash due to the ref not being set
Verified happy path works as expected with invalid/valid answers.
> FEV-1520 Fix regression caused by previous checkin

- FluStudy_us/android/app/src/main/java/host/exp/exponent/DetectorView.java
- FluStudy_us/android/app/src/main/java/host/exp/exponent/tracking/InterpretationTracker.java
I realized that we may want to be able to go back and run new phase 2 models on our production images, and so should only do the debug interpretation drawing when in debug mode. Will log the full results from the interpretation phase in a follow up pr so that we could reconstruct this if desired offline
> Only draw interpretation results on test area bitmap when in debug mode

- FluStudy_us/android/app/src/main/java/host/exp/exponent/DetectorView.java
- FluStudy_us/android/app/src/main/java/host/exp/exponent/tracking/RDTTracker.java
I should have checked the test area locations in flu-rdt/feature-map.json when I updated the strip width in https://github.com/AudereNow/audere/pull/510. With this update, all values from the feature-map match what we have in the Android code.
The extractor script grabs more of the test area which seems useful in case there is any amount of vertical offset from center. Regardless, the device extraction logic should match whatever was done to the training data.
> Update phase 2 extraction to match current python version

- FluStudy_us/android/app/src/main/java/host/exp/exponent/CameraApi2Controller.java
For https://auderenow.atlassian.net/browse/FEV-1552 -- we have multiple crash logs of attempts to close the camera when it's already closed. We should swallow that exception and continue
> Catch camera already closed exceptions

- FluApi/db/migrations/nonpii/20200117003112-fix-chills-column.js
Created with a different name here:
https://github.com/AudereNow/audere/blob/d5223c6c14f477eb9a49cf43084bfede3721dcf5/FluApi/db/migrations/nonpii/20191022105323-create-chills-tables.js#L76
Used here:
https://github.com/AudereNow/audere/blob/d5223c6c14f477eb9a49cf43084bfede3721dcf5/FluApi/src/endpoints/chillsApi.ts#L111
Discovered this issue while investigating FEV-1577, but I'm pretty sure it's unrelated.
> Fix column name in chills photo upload log

- FluStudy_us/src/i18n/locales/en.json
- FluStudy_us/src/resources/ScreenConfig.ts
- FluStudy_us/src/util/fluResults.ts
For users who go through the new RDT scan with previewFrameRate > 0, we want to change the current message of "Photo captured" and "Your test strip photo was captured successfully." on the confirmation screen, because it conflicts with the preceding message that the app would take multiple photos during the scanning process. 
Originally wanted to change Title to "Scanning complete", but that would require adding the textVariablesFn instrumentation into Title. So instead using "Test strip captured" title for either case. 
Note: This is not perfect because if the user tries RDT scan but fails, and takes a photo, we just show them "Photo captured" and "Your test strip photo was captured successfully." But can't think of better text to show in this case.
> FEV-1659 "Photo captured" screen text diverges

- FluStudy_us/ios/fluathome/FirebaseStorageUploadModule.mm
Forgot to add the new removeOriginal parameter to the iOS implementation of add() in https://github.com/AudereNow/audere/pull/589
> Add missing parameter in iOS to RN bridge method add()

- FluStudy_us/android/app/src/main/java/host/exp/exponent/DetectorView.java
- FluStudy_us/android/app/src/main/java/host/exp/exponent/RDTReader.java
- FluStudy_us/android/app/src/main/java/host/exp/exponent/RDTReaderManager.java
- FluStudy_us/src/native/rdtReader.tsx
- FluStudy_us/src/ui/components/flu/AndroidRDTReader.tsx
Changes the control flow for the reader to first open the RDT reader and initialize the camera, then (if sample rate > 0) show the 'start scan' dialog, then finally begin processing the frames. This way the user can see their strip underneath the dialog before they hit start (but we are not capturing anything before they explicitly begin the scan)
> Process frames after user agrees to start scan

- FluApi/src/endpoints/webPortal/metrics.ts
Monica and Ivan at SFS would like an additional column in the report that shows when the user uploaded the image from the first test. I used the "cleanFirstTest" screen since it immediately follows image upload (which some users skipped).
> FEV-1807: add photo finished timestamp to fever metrics report
